# Generated by Django 5.2.10 on 2026-01-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_post_category_alter_post_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
